# Copyright 1999-2014 Gentoo Foundation
# Distributed under the terms of the GNU General Public License v2
# $Header: /var/cvsroot/gentoo-x86/dev-haskell/yesod-auth/yesod-auth-1.1.7.ebuild,v 1.2 2014/07/25 09:16:29 slyfox Exp $

EAPI=5

# ebuild generated by hackport 0.3.2.9999

CABAL_FEATURES="lib profile haddock hoogle hscolour"
inherit haskell-cabal

DESCRIPTION="Authentication for Yesod"
HOMEPAGE="http://www.yesodweb.com/"
SRC_URI="mirror://hackage/packages/archive/${PN}/${PV}/${P}.tar.gz"

LICENSE="MIT"
SLOT="0/${PV}"
KEYWORDS="~amd64 ~x86"
IUSE=""

RDEPEND=">=dev-haskell/aeson-0.5:=[profile?]
		>=dev-haskell/authenticate-1.3:=[profile?]
		>=dev-haskell/blaze-html-0.5:=[profile?]
		>=dev-haskell/blaze-markup-0.5.1:=[profile?]
		dev-haskell/file-embed:=[profile?]
		=dev-haskell/hamlet-1.1*:=[profile?]
		>=dev-haskell/http-conduit-1.5:=[profile?]
		dev-haskell/http-types:=[profile?]
		>=dev-haskell/lifte# Copyright 1999-2014 Gentoo Foundation
# Distributed under the terms of the GNU General Public License v2
# $Header: /var/cvsroot/gentoo-x86/dev-haskell/yesod-auth/yesod-auth-1.1.7.ebuild,v 1.2 2014/07/25 09:16:29 slyfox Exp $

EAPI=5

# ebuild generated by hackport 0.3.2.9999

CABAL_FEATURES="lib profile haddock hoogle hscolour"
inherit haskell-cabal

DESCRIPTION="Authentication for Yesod"
HOMEPAGE="http://www.yesodweb.com/"
SRC_URI="mirror://hackage/packages/archive/${PN}/${PV}/${P}.tar.gz"

LICENSE="MIT"
SLOT="0/${PV}"
KEYWORDS="~amd64 ~x86"
IUSE=""

RDEPEND=">=dev-haskell/aeson-0.5:=[profile?]
		>=dev-haskell/authenticate-1.3:=[profile?]
		>=dev-haskell/blaze-html-0.5:=[profile?]
		>=dev-haskell/blaze-markup-0.5.1:=[profile?]
		dev-haskell/file-embed:=[profile?]
		=dev-haskell/hamlet-1.1*:=[profile?]
		>=dev-haskell/http-conduit-1.5:=[profile?]
		dev-haskell/http-types:=[profile?]
		>=dev-haskell/lifted-base-0.1:=[profile?]
		>=dev-haskell/mime-mail-0.3:=[profile?]
		dev-haskell/network:=[profile?]
		>=dev-haskell/persistent-1.0:=[profile?