# Copyright 1999-2012 Gentoo Foundation
# Distributed under the terms of the GNU General Public License v2
# $Header: /var/cvsroot/gentoo-x86/dev-haskell/wxdirect/wxdirect-0.13.1.2.ebuild,v 1.1 2012/12/27 02:55:18 gienah Exp $

EAPI=5

# ebuild generated by hackport 0.3.9999

WX_GTK_VER="2.8"

CABAL_FEATURES="bin lib profile haddock hoogle hscolour"
inherit base haskell-cabal

DESCRIPTION="helper tool for building wxHaskell"
HOMEPAGE="http://haskell.org/haskellwiki/WxHaskell"
SRC_URI="mirror://hackage/packages/archive/${PN}/${PV}/${P}.tar.gz"

LICENSE="BSD"
SLOT="${WX_GTK_VER}/${PV}"
KEYWORDS="~amd64 ~ppc ~sparc ~x86"
IUSE=""

RDEPEND=">=dev-haskell/parsec-2.1.0:=[profile?]
		<dev-haskell/parsec-4:=[profile?]
		>=dev-haskell/strict-0.3:=[profile?]
		<dev-haskell/strict-1.0:# Copyright 1999-2012 Gentoo Foundation
# Distributed under the terms of the GNU General Public License v2
# $Header: /var/cvsroot/gentoo-x86/dev-haskell/wxdirect/wxdirect-0.13.1.2.ebuild,v 1.1 2012/12/27 02:55:18 gienah Exp $

EAPI=5

# ebuild generated by hackport 0.3.9999

WX_GTK_VER="2.8"

CABAL_FEATURES="bin lib profile haddock hoogle h